=== hmrc/mtd-sa-test-support-api/resources/public/api/conf/1.0/schemas/businesses/create_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Create a Test Business",
  "type": "object",
  "properties": {
    "typeOfBusiness": {
      "type": "string",
      "description": "The type of business income source.",
      "enum": [
        "self-employment",
        "uk-property",
        "foreign-property",
        "property-unspecified"
      ]
    },
    "tradingName": {
      "type": "string",
      "description": "The trading name of the business.\n\nForbidden for property businesses.\n\nMandatory for self-employment businesses.",
      "example": "ABC Ltd."
    },
    "firstAccountingPeriodStartDate": {
      "type": "string",
      "description": "The first accounting period start date",
      "format": "YYYY-MM-DD",
      "example": "2019-09-30"
    },
    "firstAccountingPeriodEndDate": {
      "type": "string",
      "description": "The first accounting period end date",
      "format": "YYYY-MM-DD",
      "example": "2020-02-29"
    },
    "latencyDetails": {
      "type": "object",
      "description": "Income source latency details",
      "properties": {
        "latencyEndDate": {
          "type": "string",
          "description": "End date of latency period for the income source.",
          "example": "2020-02-27",
          "format": "YYYY-MM-DD"
        },
        "taxYear1": {
          "type": "string",
          "description": "First tax year for the income source.",
          "example": "2018-19",
          "format": "YYYY-YY",
          "minimum": 7,
          "maximum": 7
        },
        "latencyIndicator1": {
          "type": "string",
          "description": "Self assessment submission frequency ('A' - Annual, 'Q' - Quarterly).",
          "enum": [
            "A",
            "Q"
          ],
          "example": "A"
        },
        "taxYear2": {
          "type": "string",
          "description": "Second tax year for the income source.",
          "example": "2019-20",
          "format": "YYYY-YY",
          "minimum": 7,
          "maximum": 7
        },
        "latencyIndicator2": {
          "type": "string",
          "description": "Self assessment submission frequency ('A' - Annual, 'Q' - Quarterly).",
          "enum": [
            "A",
            "Q"
          ],
          "example": "A"
        }
      },
      "required": [
        "latencyEndDate",
        "taxYear1",
        "latencyIndicator1",
        "taxYear2",
        "latencyIndicator2"
      ]
    },
    "accountingType": {
      "description": "CASH if you used the cash basis, money actually received and paid out, to calculate your income and expenses. Otherwise ACCRUALS.",
      "type": "string",
      "enum": [
        "CASH",
        "ACCRUALS"
      ]
    },
    "commencementDate": {
      "description": "Business start date, must be in the past.",
      "type": "string",
      "format": "YYYY-MM-DD",
      "example": "2016-09-24"
    },
    "cessationDate": {
      "description": "Business cessation date.",
      "type": "string",
      "format": "YYYY-MM-DD",
      "example": "2020-03-24"
    },
    "businessAddressLineOne": {
      "description": "First line of the business address.\n\nForbidden for property businesses.\n\nMandatory for self-employment businesses.",
      "type": "string",
      "maximum": 35,
      "example": "1 ABC Rd."
    },
    "businessAddressLineTwo": {
      "description": "Second line of the business address.\n\nForbidden for property businesses.",
      "type": "string",
      "maximum": 35,
      "example": "London"
    },
    "businessAddressLineThree": {
      "description": "\t\nThird line of the business address.\n\nForbidden for property businesses.",
      "type": "string",
      "maximum": 35,
      "example": "Greater London"
    },
    "businessAddressLineFour": {
      "description": "Fourth line of the business address.\n\nForbidden for property businesses.",
      "type": "string",
      "maximum": 35,
      "example": "United Kingdom"
    },
    "businessAddressPostcode": {
      "description": "Business postcode. Forbidden for property businesses.\n\nMandatory for self-employment businesses if businessAddressCountryCode \"GB\" is provided.",
      "pattern": "^[A-Z]{1,2}[0-9][0-9A-Z]?\\s?[0-9][A-Z]{2}|BFPO\\s?[0-9]{1,10}$",
      "type": "string",
      "example": "M1 1AG"
    },
    "businessAddressCountryCode": {
      "description": "The two letter code for a country must adhere to ISO 3166. Forbidden for property businesses.\n\nMandatory for self-employment businesses.",
      "type": "string",
      "example": "GB"
    }
  },
  "required": [
    "typeOfBusiness"
  ],
  "additionalProperties": false
}

=== hmrc/mtd-sa-test-support-api/resources/public/api/conf/1.0/examples/businesses/create_request_foreign_property.json
{
  "typeOfBusiness": "foreign-property",
  "firstAccountingPeriodStartDate": "2021-04-06",
  "firstAccountingPeriodEndDate": "2022-04-05",
  "latencyDetails": {
    "latencyEndDate": "2023-04-06",
    "taxYear1": "2021-22",
    "latencyIndicator1": "A",
    "taxYear2": "2022-23",
    "latencyIndicator2": "Q"
  },
  "accountingType": "CASH",
  "commencementDate": "2020-04-06",
  "cessationDate": "2025-04-06"
}

=== hmrc/mtd-sa-test-support-api/resources/public/api/conf/1.0/examples/businesses/create_request_self_employment_business.json
{
  "typeOfBusiness": "self-employment",
  "tradingName": "MyBusiness Pvt Ltd",
  "firstAccountingPeriodStartDate": "2020-04-06",
  "firstAccountingPeriodEndDate": "2021-04-05",
  "latencyDetails": {
    "latencyEndDate": "2022-04-06",
    "taxYear1": "2020-21",
    "latencyIndicator1": "A",
    "taxYear2": "2021-22",
    "latencyIndicator2": "Q"
  },
  "accountingType": "CASH",
  "commencementDate": "2020-04-06",
  "cessationDate": "2025-04-06",
  "businessAddressLineOne": "221b Baker Street",
  "businessAddressLineTwo": "Marylebone",
  "businessAddressLineThree": "London",
  "businessAddressLineFour": "England",
  "businessAddressPostcode": "NW1 6XE",
  "businessAddressCountryCode": "GB"
}
